# Generated by Django 4.1.4 on 2023-02-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_offer_package_map_link_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageevent',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='packagegallery',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
