# Generated by Django 4.1.4 on 2023-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('persons', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('Departure_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DriverGallery',
        ),
    ]
