# Generated by Django 4.1.4 on 2023-02-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_bookdriver_delete_drivergallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcharge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
