# Generated by Django 4.1.4 on 2023-02-22 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_carcharge_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='surroundings',
            new_name='experience',
        ),
    ]
