# Generated by Django 4.1.4 on 2023-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_surroundings_review_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comfort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='facilities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
