# Generated by Django 4.1.4 on 2023-04-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_driver_rating_driverreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='driver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='driverSelect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.driver'),
        ),
    ]
