# Generated by Django 4.1.4 on 2023-04-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_review_driver_review_driverselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='no_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
