# Generated by Django 4.1.4 on 2023-04-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_driver_no_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='no_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
